---
- name: Testing Handlers
  hosts: all
  force_handlers: true
  tasks:
  - block:
    - name: Install 7zip
      win_chocolatey:
        name: flashplayerpp
        state: present
    rescue:
    - name: Install 7zip
      win_chocolatey:
        name: flashplayerppapi
        state: absent


