---
- name: Testing Complex condition with loop
  hosts: all
  vars:
    my_package:
    - jre8
    - javaruntime-preventasktoolbar
    - dropbox
  tasks:
  - name: Install packages
    win_chocolatey:
      name: "{{ item }}"
      state: present
      loop: "{{ my_package }}"
    when: 
    - ansible_facts['distribution'] == "Microsoft Windows Server 2016 Core" or condition ==value
    - ansible_facts['distribution'] == "64-bit" 
    - condition3 == value 