---
- name: Testing Complex condition with loop
  hosts: all
  vars:
    my_package:
    - jre8
    - javaruntime-preventasktoolbar
    - dropbox
  tasks:
  - name: Install packages
    win_chocolatey:
      name: "{{ item }}"
      state: present
      loop: "{{ my_package }}"
    when: ansible_facts['distribution'] == "Microsoft Windows Server 2016 Core" or ansible_facts['distribution'] == "Microsoft Windows Server 2016 Datacenter" or ansible_facts['distribution'] == "Microsoft Windows Server 2012 Core" or ansible_facts['distribution'] == "Microsoft Windows Server 2012 Datacenter"
...