---
- name: Testing Handlers
  hosts: all
  tasks:
  - name: Install Dotnet4.6.1
    win_chocolatey:
      name: dotnet4.6.1
      state: present
    notify:
    - reboot server
  - name: failling the task
    debug:   
      msg: failling TASK
    failed_when: true
  - name: This is another task
    debug:
      final task  
  handlers:
  - name: reboot server
    win_reboot:
...